database:
  host: localhost
  port: 3306
  user: root
  password: ghost
  name: foodly

table_aliment: aliment
table_utilisateur: utilisateur

select_col:
  - nom
  - marque
  - sucre
  - calories
  - graisses
  - proteines
  - bio